# Generated by Django 4.1.3 on 2022-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorevent',
            name='day_of_the_week',
            field=models.IntegerField(default=-1),
        ),
    ]
